# Generated by Django 3.0.5 on 2020-08-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('air_pressure_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('air_temp_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('avg_wind_direction_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('avg_wind_speed_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('max_wind_direction_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('max_wind_speed_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('rain_accumulation_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('rain_duration_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('relative_humidity_9am', models.DecimalField(decimal_places=12, max_digits=12)),
                ('relative_humidity_3pm', models.DecimalField(decimal_places=12, max_digits=12)),
            ],
        ),
    ]
