# Generated by Django 3.0.5 on 2020-08-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_measurement_dataset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='air_pressure_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='air_temp_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='avg_wind_direction_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='avg_wind_speed_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='max_wind_direction_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='max_wind_speed_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rain_accumulation_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='rain_duration_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='relative_humidity_3pm',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='relative_humidity_9am',
            field=models.DecimalField(decimal_places=12, max_digits=19),
        ),
    ]
